name: 'Test Bithack'

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: |
          sudo apt update
          sudo apt install libncurses-dev gcc clang make -y
      - name: Run CTest
        run: |
          make test
